### ISSUE TITLE
Missing residues

### ISSUE THREAD

**Issue by skodapetr** [skodapetr/p2rank-funpdbe#1] opened 2018-12-30 14:08 UTC
For PDB ID 1AD8 we got:
```Conversion failed for 1AD8 : Missing residue H_60A```

**Comment by rdk** [comment] 2019-01-03 17:01
This is related to the bug in P2Rank where insertion code ('A' in this case) was not included in `*_residues.csv` output file. 
The bug has been now fixed: the column **residue_num** in `*_residues.csv` has been renamed to **residue_label** and contains data in format: `"<seq.number><ins.code>"`.

Note: `*_predictions.csv` output files contain residue unique identifiers in format: `"<chain>_<seq.number><ins.code>"`. 

Note 2: In `*_predictions.csv` one residue can belong to multiple pockets. This is not a bug; primary representation of pockets in P2Rank is a cluster of Solvent Accessible Surface points and `*_predictions.csv` contains residues with certain distance threshold for each cluster. In `*_residues.csv` the residue-pocket assignment is unique -- residue belongs to at most one pocket (in case of conflict the pocket with highest score is used).

**Closed as completed** 2019-01-04 07:57 UTC
Labels: bug
